# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MLa_5_xtWiNYwH0rY1HbyQItmhpS8OXP
"""

import torch
import torch.nn as nn
from pytorch_tabnet.tab_model import TabNetClassifier

class TabNetWithDropout(TabNetClassifier):
    def __init__(self, dropout, *args, **kwargs):
        super(TabNetWithDropout, self).__init__(*args, **kwargs)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        x = super(TabNetWithDropout, self).forward(x)
        x = self.dropout(x)
        return x